blog/urls.py
from django.urls import path

from .views import render_posts, post_detail

app_name = 'blog'
urlpatterns = [
    path('', render_posts, name='posts'),
    path('<int:post_id>', post_detail, name='post_detail'),
]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls') )
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime
from django.db.models.fields.files import ImageField

class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = ImageField(upload_to='blog/images/')
    date = models.DateField(datetime.date.today)

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField
from django.db.models.fields.files import ImageField


class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=100)
    image = ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post


def render_posts(request):
    post = Post.objects.all()
    return render(request, 'posts.html', { 'post': post })

def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'post_detail.html', { 'post': post })

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()

    return render(request, 'home.html', { 'projects': projects })

blog/templates/post_detail.html
{% extends 'layout.html' %}

{% block content %}
    <div class="text-center bg-dark">
        <h2>{{post.title}}</h2>
        <h3 class="my-2 h5 text-muted">{{post.date|date:'F jS Y'}}</h3>

        <img src='{{post.image.url}}' alt='{{post.title}}' class="img-fluid">

        <div class="my-4">
            <p>{{post.description|safe}}</p>    
        </div>
    </div>    
    

{% endblock  %}

blog/templates/posts.html
{% extends 'layout.html' %}

{% block content %}

    <h1>Posts</h1>

    
    {% for post in post %}
        <div class="p-3">
            <div class="card card-body bg-black">
                <div class="row">
                    <div class="col-3">
                        <img src='{{post.image.url}}' alt='{{post.title}}' class="img-fluid">  
                    </div>

                    <div class="col-9">
                        <h2>{{post.title}}</h2>
                        <p>{{post.description|striptags|truncatechars:200}}</p>
                        <p>{{post.date|date:'M d Y'}}</p>
                        
                        <a href='{% url 'blog:post_detail' post.id %}' class="btn btn-primary" >Leer más</a> 
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock %}

portfolio/templates/home.html
{% extends 'layout.html' %}

{% block content %}

{% load static %}

<header class="row bg-dark rounded-0" >
    <div class="col-md-4" style="padding-left: 0px">
        <img src="{% static 'portfolio/yo.jpg' %}" alt="" width="200px">
    </div>
    <div class="col-md-8 my-auto">
        <h1>Alain Gamarov</h1>
        <p>Yo sólo quería escribir.</p>
    </div>
</header>
<br>
<br>
    <div class="row my-4 text-center" >
        <h3 class="text-secondary">MIS HISTORIAS</h3>

        {% for project in projects %}
            <div class="col-md-4 p-4">
                <div class="card bg-dark card-project">
                    <img src='{{ project.image.url }}' alt='{{project.title}}' class="card-img-top"/>
                    <div class="card-body">
                        <h2>{{project.title}}</h2>
                        <p>{{project.description}}</p>
                        
                        {% if project.url %}
                            <a href='{{project.url}}' class="btn btn-dark bg-danger rounded-1 btn-sm" target="_blank">visit</a>
                        {% endif %}
                    </div>
                </div>
            </div>

        {% endfor %}
    </div>

{% endblock %}

portfolio/templates/layout.html
{% load static %}

<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Alain Gamarov</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body class="text-light bg-light">
    {% include 'partials/navbar.html' %}

    <div class="container p-4">
        {% block content  %}
        
        {% endblock  %}
    </div>
    
    
</body>
</html>

portfolio/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand fw-bold fst-italic" href="/">AG</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:posts' %}">Blog</a>
          </li>
          <li class="nav-item d-flex align-items-center">
            <!--<a class="btn btn-primary btn-sm" 
                href="{% static 'portfolio/CarlosGamarra-CV.pdf' %}"
                target="_blank"
            >
                Download
            </a>-->
          </li>
        </ul>
      </div>
    </div>
  </nav>